services:
  
  # ---
  # TEMPO
  # ---
  tempo:
    image: grafana/tempo:latest
    command: ["-config.file=/etc/tempo.yaml"]
    volumes:
      - ./conf/tempo.yaml:/etc/tempo.yaml
      - ./obsv-data/tempo:/tmp/tempo
    ports:
      - "3200:3200"   # tempo frontend
  
  # ---
  # LOKI
  # ---
  loki:
    image: grafana/loki:latest
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - "3100:3100"
    volumes:
      - ./obsv-data/loki:/loki

  # --- 
  # PROMETHEUS
  # ---
  prometheus:
    image: prom/prometheus:latest
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.enable-remote-write-receiver'
    volumes:
      - ./conf/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./obsv-data/prometheus:/prometheus
    ports:
      - "9090:9090"

  # ---
  # ALLOY
  # ---
  alloy:
    image: grafana/alloy:latest
    command:
      - run
      - /etc/alloy/config.alloy
      - --server.http.listen-addr=0.0.0.0:12345
    volumes:
      - ./conf/config.alloy:/etc/alloy/config.alloy
    ports:
      - "12345:12345"  # alloy interface
      - "4317:4317"    # otlp grpc receiver
      - "4318:4318"    # otlp http receiver
    depends_on:
      - loki
      - tempo
      - prometheus
  
  # --- 
  # GRAFANA
  # ---
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    volumes:
      - ./obsv-data/grafana:/var/lib/grafana
      - ./conf/grafana-datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
    depends_on:
      - loki
      - tempo
      - prometheus

# volumes:
#   tempo-data:
#   loki-data:
#   prometheus-data:
#   grafana-data:
