services: 
  tempo:
    image: grafana/tempo:latest
    command: ["-config.file=/etc/tempo.yaml"]
    volumes:
      - ./conf/tempo.yaml:/etc/tempo.yaml
      - ./obsv-data/tempo:/tmp/tempo
    networks:
      - observability
    # ports:
    #   - "3200:3200"   # tempo frontend
    #   - "3201:3201"   # tempo metrics

  # pyroscope:
  #   image: grafana/pyroscope:latest
  #   volumes:
  #     - ./obsv-data/pyroscope:/pyroscope
  #   networks:
  #     - observability
  
  loki:
    image: grafana/loki:latest
    volumes:
      - ./obsv-data/loki:/loki
    networks:
      - observability
    # ports:
    #   - "3100:3100"

  prometheus:
    image: prom/prometheus:latest
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.enable-remote-write-receiver'
    volumes:
      - ./conf/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./obsv-data/prometheus:/prometheus
    networks:
      - observability
    # ports:
    #   - "9090:9090"

  alloy:
    image: grafana/alloy:latest
    command:
      - run
      - /etc/alloy/config.alloy
      - --server.http.listen-addr=0.0.0.0:12345
    volumes:
      - ./conf/config.alloy:/etc/alloy/config.alloy
    networks: 
      - observability
      - ingest
    depends_on:
      - loki
      - tempo
      - prometheus
    ports:
      - "127.0.0.1:12345:12345"  # alloy interface
      - "127.0.0.1:4317:4317"    # otlp grpc receiver
      - "127.0.0.1:4318:4318"    # otlp http receiver
  
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_AUTH_ANONYMOUS_ENABLED=false
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}

    volumes:
      - ./obsv-data/grafana:/var/lib/grafana
      - ./conf/grafana-datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
    networks:
      - observability
      - ingest
    depends_on:
      - loki
      - tempo
      - prometheus

networks:
  observability:
    internal: true
  ingest:
    external: true
    name: otel-ingest
